Repository m1naworld/hanghae-instagram-api, pull requests merged in 2022-12, with the labels that each got.

#2 ✨ Feat : Entity 생성
  src/main/java/com/hanghae/instagram/comment/entity/Comment.java
  src/main/java/com/hanghae/instagram/common/entity/Timestamped.java
  src/main/java/com/hanghae/instagram/like/entity/CommentLike.java
  src/main/java/com/hanghae/instagram/like/entity/PostingLike.java
  src/main/java/com/hanghae/instagram/member/entity/Member.java
  src/main/java/com/hanghae/instagram/posting/entity/Posting.java
Labels: feature

#3 ✨ Feat: Common Package 구성
  src/main/java/com/hanghae/instagram/common/exception/ErrorCode.java
  src/main/java/com/hanghae/instagram/common/exception/ErrorResponse.java
  src/main/java/com/hanghae/instagram/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hanghae/instagram/common/response/SuccessCode.java
  src/main/java/com/hanghae/instagram/common/response/SuccessResponse.java
Labels: feature

#8 ✨ Feat: CustomException
  src/main/java/com/hanghae/instagram/common/exception/CustomException.java
  src/main/java/com/hanghae/instagram/common/exception/CustomExceptionHandler.java
Labels: feature

#10 ✨ Feat : EC2 RDS MYSQL 서버 환경설정
  .gitignore
  build.gradle
Labels: feature

#13 ♻️ Refactor : InstagramApplication 내 @EnableJpaAuditing 추가
  src/main/java/com/hanghae/instagram/InstagramApplication.java
Labels: refactor

#14 ✨ Feat: Posting관련 Entity 구현
  src/main/java/com/hanghae/instagram/common/response/DataResponse.java
  src/main/java/com/hanghae/instagram/common/response/SuccessResponse.java
  src/main/java/com/hanghae/instagram/posting/entity/ImgMemberTag.java
  src/main/java/com/hanghae/instagram/posting/entity/Posting.java
  src/main/java/com/hanghae/instagram/posting/entity/PostingHashTag.java
  src/main/java/com/hanghae/instagram/posting/entity/PostingImg.java
  src/main/java/com/hanghae/instagram/posting/entity/PostingMemberTag.java
Labels: help wanted, feature

#17 ✨ Feat : CI 구축
  .github/워크플로/gradle.yml
Labels: feature

#18 ✨ Feat : CI / CD 환경설정
  .github/workflows/gradle.yml
  .github/워크플로/gradle.yml
  .gitignore
  appspec.yml
  build.gradle
  build.gradle.kts
  scripts/start.sh
  scripts/stop.sh
  settings.gradle
  src/main/resources/application.properties
Labels: feature

#21 ♻️ Refactor : application properties 변경
  src/main/resources/application.properties
Labels: bug, refactor

#24 ✨ Feat : CI CD secret 추가
  .github/workflows/gradle.yml
  .gitignore
Labels: feature

#26 ✨ Feat: PropertyValueException 핸들러 추가
  src/main/java/com/hanghae/instagram/common/exception/ErrorExceptionHandler.java
  src/main/java/com/hanghae/instagram/common/exception/ErrorResponse.java
Labels: feature

#29 ✨ Feat : 회원가입 구현
  src/main/java/com/hanghae/instagram/common/exception/ErrorCode.java
  src/main/java/com/hanghae/instagram/member/controller/MemberController.java
  src/main/java/com/hanghae/instagram/member/dto/RequestSignupMemberDto.java
  src/main/java/com/hanghae/instagram/member/entity/Member.java
  src/main/java/com/hanghae/instagram/member/mapper/MemberMapper.java
  src/main/java/com/hanghae/instagram/member/repository/MemberRepository.java
  src/main/java/com/hanghae/instagram/member/service/MemberService.java
Labels: feature

#32 ♻️ Refactor: 브라우저 상태 코드 직접 설정하도록 변경
  src/main/java/com/hanghae/instagram/common/exception/ErrorCode.java
  src/main/java/com/hanghae/instagram/common/exception/ErrorResponse.java
Labels: feature

#33 ✨ Feat : 로그인 기능 구현
  build.gradle
  src/main/java/com/hanghae/instagram/common/exception/ErrorCode.java
  src/main/java/com/hanghae/instagram/jwt/JwtUtil.java
  src/main/java/com/hanghae/instagram/member/controller/MemberController.java
  src/main/java/com/hanghae/instagram/member/dto/RequestLoginMemberDto.java
  src/main/java/com/hanghae/instagram/member/service/MemberService.java
Labels: feature

#34 ✨ Feat: Posting Create, Show 기능 구현
  build.gradle
  src/main/java/com/hanghae/instagram/InstagramApplication.java
  src/main/java/com/hanghae/instagram/common/response/SuccessCode.java
  src/main/java/com/hanghae/instagram/posting/controller/PostingController.java
  src/main/java/com/hanghae/instagram/posting/dto/createPosting/CreatePostingDto.java
  src/main/java/com/hanghae/instagram/posting/dto/createPosting/CreatePostingImgDto.java
  src/main/java/com/hanghae/instagram/posting/dto/createPosting/CreatePostingImgMemberTagDto.java
  src/main/java/com/hanghae/instagram/posting/dto/createPosting/RequestCreatePostingDto.java
  src/main/java/com/hanghae/instagram/posting/dto/createPosting/RequestCreatePostingImgDto.java
  src/main/java/com/hanghae/instagram/posting/dto/createPosting/RequestCreatePostingImgMemberTagDto.java
  src/main/java/com/hanghae/instagram/posting/dto/showPosting/ResponseShowPostingDto.java
  src/main/java/com/hanghae/instagram/posting/dto/showPosting/ShowPostingDto.java
  src/main/java/com/hanghae/instagram/posting/dto/showPosting/ShowPostingImgDto.java
  src/main/java/com/hanghae/instagram/posting/dto/showPosting/ShowPostingImgMemberTagDto.java
  src/main/java/com/hanghae/instagram/posting/entity/Posting.java
  src/main/java/com/hanghae/instagram/posting/entity/PostingHashTag.java
  src/main/java/com/hanghae/instagram/posting/entity/PostingImg.java
  src/main/java/com/hanghae/instagram/posting/entity/PostingImgMemberTag.java
  src/main/java/com/hanghae/instagram/posting/entity/PostingMemberTag.java
  src/main/java/com/hanghae/instagram/posting/mapper/CreatePostingMapper.java
  src/main/java/com/hanghae/instagram/posting/mapper/ShowPostingMapper.java
  src/main/java/com/hanghae/instagram/posting/repository/PostingHashTagRepository.java
  src/main/java/com/hanghae/instagram/posting/repository/PostingImgMemberTagRepository.java
  src/main/java/com/hanghae/instagram/posting/repository/PostingImgRepository.java
  src/main/java/com/hanghae/instagram/posting/repository/PostingMemberTagRepository.java
  src/main/java/com/hanghae/instagram/posting/repository/PostingRepository.java
  src/main/java/com/hanghae/instagram/posting/service/PostingService.java
  src/main/resources/application-h2.properties
  src/main/resources/json/memberData.json
Labels: feature

#37 ✨ Feat: 시큐리티 적용 및 CORS
  build.gradle
  src/main/java/com/hanghae/instagram/member/dto/RequestSignupMemberDto.java
  src/main/java/com/hanghae/instagram/member/entity/Member.java
  src/main/java/com/hanghae/instagram/member/mapper/MemberMapper.java
  src/main/java/com/hanghae/instagram/member/service/MemberService.java
  src/main/java/com/hanghae/instagram/security/config/WebSecurityConfig.java
  src/main/java/com/hanghae/instagram/security/jwt/JwtAuthFilter.java
  src/main/java/com/hanghae/instagram/security/jwt/JwtUtil.java
  src/main/java/com/hanghae/instagram/security/userdetails/UserDetailsImpl.java
  src/main/java/com/hanghae/instagram/security/userdetails/UserDetailsServiceImpl.java
Labels: feature

#35 ✨ Feat : 댓글 작성 API
  src/main/java/com/hanghae/instagram/comment/controller/CommentController.java
  src/main/java/com/hanghae/instagram/comment/dto/RequestComment.java
  src/main/java/com/hanghae/instagram/comment/dto/ResponseComment.java
  src/main/java/com/hanghae/instagram/comment/entity/Comment.java
  src/main/java/com/hanghae/instagram/comment/repository/CommentRepository.java
  src/main/java/com/hanghae/instagram/comment/service/CommentService.java
  src/main/java/com/hanghae/instagram/common/response/SuccessCode.java
Labels: feature

#40 Refactor : SuccessCode 수정, 추가
  src/main/java/com/hanghae/instagram/common/response/SuccessCode.java
Labels: refactor

#41 ✨ Feat: 좋아요 기능
  src/main/java/com/hanghae/instagram/comment/entity/Comment.java
  src/main/java/com/hanghae/instagram/common/exception/ErrorCode.java
  src/main/java/com/hanghae/instagram/common/response/SuccessCode.java
  src/main/java/com/hanghae/instagram/like/controller/LikeController.java
  src/main/java/com/hanghae/instagram/like/dto/RequestLikeDto.java
  src/main/java/com/hanghae/instagram/like/dto/ResponseLikeDto.java
  src/main/java/com/hanghae/instagram/like/entity/CommentLike.java
  src/main/java/com/hanghae/instagram/like/entity/PostingLike.java
  src/main/java/com/hanghae/instagram/like/repository/CommentLikeRepository.java
  src/main/java/com/hanghae/instagram/like/repository/PostingLikeRepository.java
  src/main/java/com/hanghae/instagram/like/service/LikeService.java
  src/main/java/com/hanghae/instagram/posting/entity/Posting.java
Labels: feature

#47 🐛 Fix : CI CD test
  build.gradle
Labels: bug

#49 ♻️ Refactor: username exception 추가
  src/main/java/com/hanghae/instagram/member/service/MemberService.java
Labels: refactor

#51 ✨ Feat: Like 도메인 기능과 서비스 연결 및 Mock data 기능 수정
  .gitignore
  src/main/java/com/hanghae/instagram/like/controller/LikeController.java
  src/main/java/com/hanghae/instagram/like/entity/PostingLike.java
  src/main/java/com/hanghae/instagram/posting/controller/PostingController.java
  src/main/java/com/hanghae/instagram/posting/entity/Posting.java
  src/main/java/com/hanghae/instagram/posting/mapper/ShowPostingMapper.java
  src/main/java/com/hanghae/instagram/posting/repository/PostingRepository.java
  src/main/java/com/hanghae/instagram/posting/service/PostingService.java
  src/main/resources/json/memberData.json
Labels: feature

#52 ✨ Feat: 프로필 이미지 랜덤지정
  src/main/java/com/hanghae/instagram/common/response/SuccessCode.java
  src/main/java/com/hanghae/instagram/member/controller/MemberController.java
  src/main/java/com/hanghae/instagram/member/dto/RequestSignupMemberDto.java
  src/main/java/com/hanghae/instagram/member/dto/ResponseMemberDto.java
  src/main/java/com/hanghae/instagram/member/entity/Member.java
  src/main/java/com/hanghae/instagram/member/mapper/MemberMapper.java
  src/main/java/com/hanghae/instagram/member/service/MemberService.java
  src/main/java/com/hanghae/instagram/security/userdetails/UserDetailsImpl.java
  src/main/java/com/hanghae/instagram/security/userdetails/UserDetailsServiceImpl.java
Labels: feature

#54 ✨ Feat: 팔로우 기능
  src/main/java/com/hanghae/instagram/common/response/SuccessCode.java
  src/main/java/com/hanghae/instagram/follow/controller/FollowController.java
  src/main/java/com/hanghae/instagram/follow/dto/RequestFollowDto.java
  src/main/java/com/hanghae/instagram/follow/dto/ResponseFollowDto.java
  src/main/java/com/hanghae/instagram/follow/entity/Follow.java
  src/main/java/com/hanghae/instagram/follow/entity/FollowCompositeKey.java
  src/main/java/com/hanghae/instagram/follow/repository/FollowRepository.java
  src/main/java/com/hanghae/instagram/follow/service/FollowService.java
  src/main/java/com/hanghae/instagram/member/entity/Member.java
Labels: feature

#53 ✨ Feat : 댓글 수정 API
  src/main/java/com/hanghae/instagram/comment/controller/CommentController.java
  src/main/java/com/hanghae/instagram/comment/dto/RequestComment.java
  src/main/java/com/hanghae/instagram/comment/dto/ResponseComment.java
  src/main/java/com/hanghae/instagram/comment/entity/Comment.java
  src/main/java/com/hanghae/instagram/comment/mapper/CommentMapper.java
  src/main/java/com/hanghae/instagram/comment/service/CommentService.java
Labels: feature

#61 ✨ Feat : 댓글 삭제 API
  src/main/java/com/hanghae/instagram/comment/controller/CommentController.java
  src/main/java/com/hanghae/instagram/comment/dto/RequestComment.java
  src/main/java/com/hanghae/instagram/comment/dto/ResponseComment.java
  src/main/java/com/hanghae/instagram/comment/mapper/CommentMapper.java
  src/main/java/com/hanghae/instagram/comment/service/CommentService.java
  src/main/java/com/hanghae/instagram/common/response/SuccessCode.java
  src/main/java/com/hanghae/instagram/member/entity/Member.java
Labels: feature

#62 ♻️ Refactor: 팔로우 userDetails 적용
  src/main/java/com/hanghae/instagram/follow/controller/FollowController.java
  src/main/java/com/hanghae/instagram/follow/dto/RequestFollowDto.java
  src/main/java/com/hanghae/instagram/follow/entity/Follow.java
  src/main/java/com/hanghae/instagram/follow/entity/FollowCompositeKey.java
  src/main/java/com/hanghae/instagram/follow/service/FollowService.java
  src/main/java/com/hanghae/instagram/member/entity/Member.java
  src/main/java/com/hanghae/instagram/member/repository/MemberRepository.java
Labels: refactor

#64 ♻️ Refactor : application.properties 수정
  .github/workflows/gradle.yml
  src/main/resources/application.properties
Labels: refactor

#66 ♻️ Refactor: 좋아요 API 수정 및 에러명 수정
  src/main/java/com/hanghae/instagram/common/exception/ErrorCode.java
  src/main/java/com/hanghae/instagram/like/controller/LikeController.java
  src/main/java/com/hanghae/instagram/like/service/LikeService.java
Labels: refactor

#69 ✨ Feat: HashTag, MemberTag 추출 기능 구현 및 DTO 반환 스타일 변경
  src/main/java/com/hanghae/instagram/posting/dto/showPosting/ResponseShowPostingDetailsDto.java
  src/main/java/com/hanghae/instagram/posting/service/PostingService.java
  src/main/java/com/hanghae/instagram/posting/service/TagExctractor.java
Labels: feature

#72 ✨ Feat, ♻️ Refactor: 유저 정보 조회
  src/main/java/com/hanghae/instagram/member/controller/MemberController.java
  src/main/java/com/hanghae/instagram/member/dto/ResponseMemberDto.java
Labels: feature, refactor

#76 ✨ Feat: 카카오로그인 구현
  src/main/java/com/hanghae/instagram/common/response/SuccessCode.java
  src/main/java/com/hanghae/instagram/member/controller/MemberController.java
  src/main/java/com/hanghae/instagram/member/dto/KakaoMemberInfoDto.java
  src/main/java/com/hanghae/instagram/member/dto/ResponseMemberDto.java
  src/main/java/com/hanghae/instagram/member/entity/Member.java
  src/main/java/com/hanghae/instagram/member/repository/MemberRepository.java
  src/main/java/com/hanghae/instagram/member/service/KakaoService.java
  src/main/java/com/hanghae/instagram/security/jwt/JwtUtil.java
  src/main/resources/application.properties
Labels: feature

#77 ♻️ Refactor : comment 이미지 반환 추가
  src/main/java/com/hanghae/instagram/comment/dto/RequestComment.java
  src/main/java/com/hanghae/instagram/comment/dto/ResponseComment.java
  src/main/java/com/hanghae/instagram/comment/entity/Comment.java
  src/main/java/com/hanghae/instagram/comment/mapper/CommentMapper.java
  src/main/java/com/hanghae/instagram/comment/service/CommentService.java
  src/main/java/com/hanghae/instagram/common/response/SuccessCode.java
  src/main/java/com/hanghae/instagram/member/entity/Member.java
Labels: refactor

#84 ✨ Feat: 프로필 이미지 반환 필드 추가
  src/main/java/com/hanghae/instagram/posting/dto/showPosting/ResponseShowPostingDetailsDto.java
  src/main/java/com/hanghae/instagram/posting/dto/showPosting/ResponseShowPostingDto.java
  src/main/java/com/hanghae/instagram/posting/dto/showPosting/ShowPostingDetailsDto.java
  src/main/java/com/hanghae/instagram/posting/dto/showPosting/ShowPostingDto.java
  src/main/java/com/hanghae/instagram/posting/mapper/ShowPostingMapper.java
Labels: feature

#86 ♻️ Refactor: WebSecurityConfig CORS 리액트 서버 추가
  src/main/java/com/hanghae/instagram/security/config/WebSecurityConfig.java
Labels: refactor

#88 ✨ Feat: 게시글 삭제 기능 구현
  .gitignore
  src/main/java/com/hanghae/instagram/comment/dto/ResponseComment.java
  src/main/java/com/hanghae/instagram/comment/entity/Comment.java
  src/main/java/com/hanghae/instagram/comment/repository/CommentRepository.java
  src/main/java/com/hanghae/instagram/comment/service/CommentService.java
  src/main/java/com/hanghae/instagram/common/response/SuccessCode.java
  src/main/java/com/hanghae/instagram/like/repository/CommentLikeRepository.java
  src/main/java/com/hanghae/instagram/like/repository/PostingLikeRepository.java
  src/main/java/com/hanghae/instagram/posting/controller/PostingController.java
  src/main/java/com/hanghae/instagram/posting/dto/showPosting/ShowPostingDetailsDto.java
  src/main/java/com/hanghae/instagram/posting/repository/PostingHashTagRepository.java
  src/main/java/com/hanghae/instagram/posting/repository/PostingImgMemberTagRepository.java
  src/main/java/com/hanghae/instagram/posting/repository/PostingImgRepository.java
  src/main/java/com/hanghae/instagram/posting/repository/PostingMemberTagRepository.java
  src/main/java/com/hanghae/instagram/posting/repository/PostingRepository.java
  src/main/java/com/hanghae/instagram/posting/service/PostingService.java
Labels: feature
